const ActionMasterType = {
    // GET_USER: 'GET_USER',
    // GET_USER_SUCCEED: 'GET_USER_SUCCEED',
    // GET_USER_FAILED: 'GET_USER_FAILED',
    //  ============= REGIONS ================ //
    GET_REGIONS: 'GET_REGIONS',
    GET_REGIONS_SUCCEED: 'GET_REGIONS_SUCCEED',
    GET_REGIONS_FAILED: 'GET_REGIONS_FAILED',
    ADD_REGIONS: 'ADD_REGIONS',
    ADD_REGIONS_SUCCEED: 'ADD_REGIONS_SUCCEED',
    ADD_REGIONS_FAILED: 'ADD_REGIONS_FAILED',
    UPDATE_REGIONS: 'UPDATE_REGIONS',
    UPDATE_REGIONS_SUCCEED: 'UPDATE_REGIONS_SUCCEED',
    UPDATE_REGIONS_FAILED: 'UPDATE_REGIONS_FAILED',
    DEL_REGIONS: 'DEL_REGIONS',
    DEL_REGIONS_SUCCEED: 'DEL_REGIONS_SUCCEED',
    DEL_REGIONS_FAILED: 'DEL_REGIONS_FAILED',

    // ============= Country ============ //
    GET_COUNTRY: 'GET_COUNTRY',
    GET_COUNTRY_SUCCEED: 'GET_COUNTRY_SUCCEED',
    GET_COUNTRY_FAILED: 'GET_COUNTRY_FAILED',
    ADD_COUNTRY: 'ADD_COUNTRY',
    ADD_COUNTRY_SUCCEED: 'ADD_COUNTRY_SUCCEED',
    ADD_COUNTRY_FAILED: 'ADD_COUNTRY_FAILED',
    UPDATE_COUNTRY: 'UPDATE_COUNTRY',
    UPDATE_COUNTRY_SUCCEED: 'UPDATE_COUNTRY_SUCCEED',
    UPDATE_COUNTRY_FAILED: 'UPDATE_COUNTRY_FAILED',
    DEL_COUNTRY: 'DEL_COUNTRY',
    DEL_COUNTRY_SUCCEED: 'DEL_COUNTRY_SUCCEED',
    DEL_COUNTRY_FAILED: 'DEL_COUNTRY_FAILED',

    // =============== Provinces =============== //
    GET_PROV: 'GET_PROV',
    GET_PROV_SUCCEED: 'GET_PROV_SUCCEED',
    GET_PROV_FAILED: 'GET_PROV_FAILED',
    ADD_PROV: 'ADD_PROV',
    ADD_PROV_SUCCEED: 'ADD_PROV_SUCCEED',
    ADD_PROV_FAILED: 'ADD_PROV_FAILED',
    UPDATE_PROV: 'UPDATE_PROV',
    UPDATE_PROV_SUCCEED: 'UPDATE_PROV_SUCCEED',
    UPDATE_PROV_FAILED: 'UPDATE_PROV_FAILED',
    DEL_PROV: 'DEL_PROV',
    DEL_PROV_SUCCEED: 'DEL_PROV_SUCCEED',
    DEL_PROV_FAILED: 'DEL_PROV_FAILED',



    // ============= address ============= //
    GET_ADDR: 'GET_ADDR',
    GET_ADDR_SUCCEED: 'GET_ADDR_SUCCEED',
    GET_ADDR_FAILED: 'GET_ADDR_FAILED',
    ADD_ADDR: 'ADD_ADDR',
    ADD_ADDR_SUCCEED: 'ADD_ADDR_SUCCEED',
    ADD_ADDR_FAILED: 'ADD_ADDR_FAILED',
    UPDATE_ADDR: 'UPDATE_ADDR',
    UPDATE_ADDR_SUCCEED: 'UPDATE_ADDR_SUCCEED',
    UPDATE_ADDR_FAILED: 'UPDATE_ADDR_FAILED',
    DEL_ADDR: 'DEL_ADDR',
    DEL_ADDR_SUCCEED: 'DEL_ADDR_SUCCEED',
    DEL_ADDR_FAILED: 'DEL_ADDR_FAILED',

    // ================  cagro =============== //
    GET_CAGRO: 'GET_CAGRO',
    GET_CAGRO_SUCCEED: 'GET_CAGRO_SUCCEED',
    GET_CAGRO_FAILED: 'GET_CAGRO_FAILED',
    ADD_CAGRO: 'ADD_CAGRO',
    ADD_CAGRO_SUCCEED: 'ADD_CAGRO_SUCCEED',
    ADD_CAGRO_FAILED: 'ADD_CAGRO_FAILED',
    UPDATE_CAGRO: 'UPDATE_CAGRO',
    UPDATE_CAGRO_SUCCEED: 'UPDATE_CAGRO_SUCCEED',
    UPDATE_CAGRO_FAILED: 'UPDATE_CAGRO_FAILED',
    DEL_CAGRO: 'DEL_CAGRO',
    DEL_CAGRO_SUCCEED: 'DEL_CAGRO_SUCCEED',
    DEL_CAGRO_FAILED: 'DEL_CAGRO_FAILED',

    // ================== Policy ============== //
    GET_POLICY: 'GET_POLICY',
    GET_POLICY_SUCCEED: 'GET_POLICY_SUCCEED',
    GET_POLICY_FAILED: 'GET_POLICY_FAILED',
    ADD_POLICY: 'ADD_POLICY',
    ADD_POLICY_SUCCEED: 'ADD_POLICY_SUCCEED',
    ADD_POLICY_FAILED: 'ADD_POLICY_FAILED',
    UPDATE_POLICY: 'UPDATE_POLICY',
    UPDATE_POLICY_SUCCEED: 'UPDATE_POLICY_SUCCEED',
    UPDATE_POLICY_FAILED: 'UPDATE_POLICY_FAILED',
    DEL_POLICY: 'DEL_POLICY',
    DEL_POLICY_SUCCEED: 'DEL_POLICY_SUCCEED',
    DEL_POLICY_FAILED: 'DEL_POLICY_FAILED',

    // =============== Price Items ======== //
    GET_PRIT: 'GET_PRIT',
    GET_PRIT_SUCCEED: 'GET_PRIT_SUCCEED',
    GET_PRIT_FAILED: 'GET_PRIT_FAILED',
    ADD_PRIT: 'ADD_PRIT',
    ADD_PRIT_SUCCEED: 'ADD_PRIT_SUCCEED',
    ADD_PRIT_FAILED: 'ADD_PRIT_FAILED',
    UPDATE_PRIT: 'UPDATE_PRIT',
    UPDATE_PRIT_SUCCEED: 'UPDATE_PRIT_SUCCEED',
    UPDATE_PRIT_FAILED: 'UPDATE_PRIT_FAILED',
    DEL_PRIT: 'DEL_PRIT',
    DEL_PRIT_SUCCEED: 'DEL_PRIT_SUCCEED',
    DEL_PRIT_FAILED: 'DEL_PRIT_FAILED',

    // Service task
    GET_SERVICETASK: 'GET_SERVICETASK',
    GET_SERVICETASK_SUCCEED: 'GET_SERVICETASK_SUCCEED',
    GET_SERVICETASK_FAILED: 'GET_SERVICETASK_FAILED',
    ADD_SERVICETASK: 'ADD_SERVICETASK',
    ADD_SERVICETASK_SUCCEED: 'ADD_SERVICETASK_SUCCEED',
    ADD_SERVICETASK_FAILED: 'ADD_SERVICETASK_FAILED',
    UPDATE_SERVICETASK: 'UPDATE_SERVICETASK',
    UPDATE_SERVICETASK_SUCCEED: 'UPDATE_SERVICETASK_SUCCEED',
    UPDATE_SERVICETASK_FAILED: 'UPDATE_SERVICETASK_FAILED',
    DEL_SERVICETASK: 'DEL_SERVICETASK',
    DEL_SERVICETASK_SUCCEED: 'DEL_SERVICETASK_SUCCEED',
    DEL_SERVICETASK_FAILED: 'DEL_SERVICETASK_FAILED',




}

export default ActionMasterType;
