const ActionTypeResto = {

  //GET URL RESTO MENUS PHOTOS

  GET_URL_PHOTOS : "GET_URL_PHOTOS",
  GET_URL_PHOTOS_SUCCED : "GET_URL_PHOTOS_SUCCED",
  GET_URL_PHOTOS_FAILED : "GET_URL_PHOTOS_FAILED",

  //GET ID TERAKHIR ORDER MENUS

  GET_ID_AKHIR_ORDER_MENUS : "GET_ID_AKHIR_ORDER_MENUS",
  GET_ID_AKHIR_ORDER_MENUS_SUCCED : "GET_ID_AKHIR_ORDER_MENUS_SUCCED",
  GET_ID_AKHIR_ORDER_MENUS_FAILED : "GET_ID_AKHIR_ORDER_MENUS_FAILED",

    // GET DATA AKHIR ORDER MENUS

    GET_AKHIR_ORDER_MENUS : "GET_AKHIR_ORDER_MENUS",
    GET_AKHIR_ORDER_MENUS_SUCCEED : "GET_AKHIR_ORDER_MENUS_SUCCEED",
    GET_AKHIR_ORDER_MENUS_FAILED : "GET_AKHIR_ORDER_MENUS_FAILED",


  //============= RESTO MENU PHOTOS ================//

  //GET FOTO
  GET_FOTO_RESTO_MENUS: "GET_FOTO_RESTO_MENUS",
  GET_FOTO_RESTO_MENUS_SUCCEED: "GET_FOTO_RESTO_MENUS_SUCCEED",
  GET_FOTO_RESTO_MENUS_FAILED: "GET_FOTO_RESTO_MENUS_FAILED",

  //UPDATE FOTO
  UPDATE_FOTO_RESTO_MENUS: "UPDATE_UPDATE_FOTO_RESTO_MENUS",
  UPDATE_FOTO_RESTO_MENUS_SUCCEED: "UPDATE_UPDATE_FOTO_RESTO_MENUS_SUCCEED",
  UPDATE_FOTO_RESTO_MENUS_FAILED: "UPDATE_UPDATE_FOTO_RESTO_MENUS_FAILED",

  //CREATE FOTO
  ADD_FOTO_RESTO_MENUS: "ADD_FOTO_RESTO_MENUS",
  ADD_FOTO_RESTO_MENUS_SUCCEED: "ADD_FOTO_RESTO_MENUS_SUCCED",
  ADD_FOTO_RESTO_MENUS_FAILED: "ADD_FOTO_RESTO_MENUS_FAILED",

  //=================== CARD ALL CLIENT ===================//
  // GET CARD ALL CLIENT
  GET_CARDRESTOMENUS: "GET_CARDRESTOMENUS",
  GET_CARDRESTOMENUS_SUCCEED: "GET_CARDRESTOMENUS_SUCCEED",
  GET_CARDRESTOMENUS_FAILED: "GET_CARDRESTOMENUS_FAILED",

  //=================== RESTO MENUS ===================//

  // Get Tabel Resto Menus
  GET_RESTOMENUS: "GET_RESTOMENUS",
  GET_RESTOMENUS_SUCCEED: "GET_RESTOMENUS_SUCCEED",
  GET_RESTOMENUS_FAILED: "GET_RESTOMENUS_FAILED",

  // Update Tabel Resto Menus
  UPDATE_RESTOMENUS: "UPDATE_RESTOMENUS",
  UPDATE_RESTOMENUS_SUCCEED: "UPDATE_RESTOMENUS_SUCCEED",
  UPDATE_RESTOMENUS_FAILED: "UPDATE_RESTOMENUS_FAILED",

  // Create Tabel Resto Menus
  ADD_RESTOMENUS: "ADD_RESTOMENUS",
  ADD_RESTOMENUS_SUCCEED: "ADD_RESTOMENUS_SUCCEED",
  ADD_RESTOMENUS_FAILED: "ADD_RESTOMENUS_FAILED",

  // Delete Tabel Resto Menus
  DEL_RESTOMENUS: "DEL_RESTOMENUS",
  DEL_RESTOMENUS_SUCCEED: "DEL_RESTOMENUS_SUCCEED",
  DEL_RESTOMENUS_FAILED: "DEL_RESTOMENUS_FAILED",

  // Find One Tabel Resto Menus
  GET_RESTOMENU: "GET_RESTOMENU",
  GET_RESTOMENU_SUCCEED: "GET_RESTOMENU_SUCCEED",
  GET_RESTOMENU_FAILED: "GET_RESTOMENU_FAILED",

  // ======================= RESTO MENU PHOTOS =======================//

  // Get Tabel Resto Menus Photos
  GET_RESTOMENUS_PHOTOS: "GET_RESTOMENUS_PHOTOS",
  GET_RESTOMENUS_PHOTOS_SUCCEED: "GET_RESTOMENUS_PHOTOS_SUCCEED",
  GET_RESTOMENUS_PHOTOS_FAILED: "GET_RESTOMENUS_PHOTOS_FAILED",

  // Update Tabel Resto Menus Photos
  UPDATE_RESTOMENUS_PHOTOS: "UPDATE_RESTOMENUS_PHOTOS",
  UPDATE_RESTOMENUS_PHOTOS_SUCCEED: "UPDATE_RESTOMENUS_PHOTOS_SUCCEED",
  UPDATE_RESTOMENUS_PHOTOS_FAILED: "UPDATE_RESTOMENUS_PHOTOS_FAILED",

  // Create Tabel Resto Menus Photos
  ADD_RESTOMENUS_PHOTOS: "ADD_RESTOMENUS_PHOTOS",
  ADD_RESTOMENUS_PHOTOS_SUCCEED: "ADD_RESTOMENUS_PHOTOS_SUCCEED",
  ADD_RESTOMENUS_PHOTOS_FAILED: "ADD_RESTOMENUS_PHOTOS_FAILED",

  // Delete Tabel Resto Menus Photos
  DEL_RESTOMENUS_PHOTOS: "DEL_RESTOMENUS_PHOTOS",
  DEL_RESTOMENUS_PHOTOS_SUCCEED: "DEL_RESTOMENUS_PHOTOS_SUCCEED",
  DEL_RESTOMENUS_PHOTOS_FAILED: "DEL_RESTOMENUS_PHOTOS_FAILED",

  // Find One Tabel Resto Menus Photos
  GET_RESTOMENU_PHOTOS: "GET_RESTOMENU_PHOTOS",
  GET_RESTOMENU_PHOTOS_SUCCEED: "GET_RESTOMENU_PHOTOS_SUCCEED",
  GET_RESTOMENU_PHOTOS_FAILED: "GET_RESTOMENU_PHOTOS_FAILED",

  //============== ORDER MENUS ====================//

  //get order menus
  GET_ORDER_MENUS: "ADD_ORDER_MENUS",
  GET_ORDER_MENUS_SUCCEED: "ADD_ORDER_MENUS_SUCCEED",
  GET_ORDER_MENUS_FAILED: "ADD_ORDER_MENUS_FAILED",

  // Create order menus
  ADD_ORDER_MENUS: "ADD_ORDER_MENUS",
  ADD_ORDER_MENUS_SUCCEED: "ADD_ORDER_MENUS_SUCCEED",
  ADD_ORDER_MENUS_FAILED: "ADD_ORDER_MENUS_FAILED",

  //============= ORDER MENU DETAIL =================//

  //ORDER DETAIL GET
  GET_ORDER_DETAIL: "GET_ORDER_DETAIL",
  GET_ORDER_DETAIL_SUCCEED: "GET_ORDER_DETAIL_SUCCEED",
  GET_ORDER_DETAIL_FAILED: "GET_ORDER_DETAIL_FAILED",
  
  //CREATE ORDER DETAIL
  ADD_ORDER_DETAIL: "ADD_ORDER_DETAIL",
  ADD_ORDER_DETAIL_SUCCEED: "ADD_ORDER_DETAIL_SUCCEED",
  ADD_ORDER_DETAIL_FAILED: "ADD_ORDER_DETAIL_FAILED",
};

export default ActionTypeResto;
