const ActionTypes = {
  // get card
  GET_CARDHOTEL: "GET_CARDHTEL",
  GET_CARDHOTEL_SUCCED: "GET_CARDHTEL_SUCCED",
  GET_CARDHOTEL_FAILED: "GET_CARDHTEL_FAILED",

  // get faciallhotel
  GET_FACIALLHOTEL: "GET_FACIALLHOTEL",
  GET_FACIALLHOTEL_SUCCED: "GET_FACIALLHOTEL_SUCCED",
  GET_FACIALLHOTEL_FAILED: "GET_FACIALLHOTEL_FAILED",

  // get hore
  GET_HORE: "GET_HORE",
  GET_HORE_SUCCED: "GET_HORE_SUCCED",
  GET_HORE_FAILED: "GET_HORE_FAILED",

  // get adminHotel
  GET_HOTELADMIN: "GET_HOTELADMIN",
  GET_HOTELADMIN_SUCCED: "GET_HOTELADMIN_SUCCED",
  GET_HOTELADMIN_FAILED: "GET_HOTELADMIN_FAILED",

  // add hotel admin
  ADD_HOTELADMIN: "ADD_HOTELADMIN",
  ADD_HOTELADMIN_SUCCED: "ADD_HOTELADMIN_SUCCED",
  ADD_HOTELADMIN_FAILED: "ADD_HOTELADMIN_FAILED",

  // delete hotel
  DEL_HOTELADMIN: "DEL_HOTELADMIN",
  DEL_HOTELADMIN_SUCCED: "DEL_HOTELADMIN_SUCCED",
  DEL_HOTELADMIN_FAILED: "DEL_HOTELADMIN_FAILED",

  // updated hotel
  UPDATE_HOTELADMIN: "UPDATE_HOTELADMIN",
  UPDATE_HOTELADMIN_SUCCED: "UPDATE_HOTELADMIN_SUCCED",
  UPDATE_HOTELADMIN_FAILED: "UPDATE_HOTELADMIN_FAILED",

  // get faci
  GET_FACIADMIN: "GET_FACIADMIN",
  GET_FACIADMIN_SUCCED: "GET_FACIADMIN_SUCCED",
  GET_FACIADMIN_FAILED: "GET_FACIADMIN_FAILED",

  // get max id room
  GET_MAXIDROOM: "GET_MAXIDROOM",
  GET_MAXIDROOM_SUCCED: "GET_MAXIDROOM_SUCCED",
  GET_MAXIDROOM_FAILED: "GET_MAXIDROOM_FAILED",

  //insert faci
  ADD_FACIADMIN: "ADD_FACIADMIN",
  ADD_FACIADMIN_SUCCED: "ADD_FACIADMIN_SUCCED",
  ADD_FACIADMIN_FAILED: "ADD_FACIADMIN_FAILED",
  // update fACI
  UPDATE_FACI: "UPDATE_FACI",
  UPDATE_FACI_SUCCED: "UPDATE_FACI_SUCCED",
  UPDATE_FACI_FAILED: "UPDATE_FACI_FAILED",
  // get search address
  GET_ADDRSEARCH: "GET_ADDRSEARCH",
  GET_ADDRSEARCH_SUCCED: "GET_ADDRSEARCH_SUCCED",
  GET_ADDRSEARCH_FAILED: "GET_ADDRSEARCH_FAILED",

  // delete afi
  DEL_FACI: "DEL_FACI",
  DEL_FACI_SUCCED: "DEL_FACI_SUCCED",
  DEL_FACI_FAILED: "DEL_FACI_FAILED",

  // get fapho
  GET_FAPHO: "GET_FAPHO",
  GET_FAPHO_SUCCED: "GET_FAPHO_SUCCED",
  GET_FAPHO_FAILED: "GET_FAPHO_FAILED",
  // get fapho
  GET_FACIPRICEHISTORY: "GET_FACIPRICEHISTORY",
  GET_FACIPRICEHISTORY_SUCCED: "GET_FACIPRICEHISTORY_SUCCED",
  GET_FACIPRICEHISTORY_FAILED: "GET_FACIPRICEHISTORY_FAILED",

  // upload fapho
  UPLOAD_FAPHO: "UPLOAD_FAPHO",
  UPLOAD_FAPHO_SUCCED: "UPLOAD_FAPHO_SUCCED",
  UPLOAD_FAPHO_FAILED: "UPLOAD_FAPHO_FAILED",
};

export default ActionTypes;
