export const FETCH_BANKS = 'FETCH_BANKS'
export const FETCH_BANKS_SUCCEED = 'FETCH_BANKS_SUCCEED'
export const FETCH_BANKS_FAILED = 'FETCH_BANKS_FAILED'

export const UPDATE_BANK = 'UPDATE_BANK'
export const UPDATE_BANK_SUCCEED = 'UPDATE_BANK_SUCCEED'
export const UPDATE_BANK_FAILED = 'UPDATE_BANK_FAILED'

export const INSERT_BANK = 'INSERT_BANK'
export const INSERT_BANK_SUCCEED = 'INSERT_BANK_SUCCEED'
export const INSERT_BANK_FAILED = 'INSERT_BANK_FAILED'

export const DELETE_BANK = 'DELETE_BANK'
export const DELETE_BANK_SUCCEED = 'DELETE_BANK_SUCCEED'
export const DELETE_BANK_FAILED = 'DELETE_BANK_FAILED'