export const FETCH_FINTECH = 'FETCH_FINTECH'
export const FETCH_FINTECH_SUCCEED = 'FETCH_FINTECH_SUCCEED'
export const FETCH_FINTECH_FAILED = 'FETCH_FINTECH_FAILED'

export const UPDATE_FINTECH = 'UPDATE_FINTECH'
export const UPDATE_FINTECH_SUCCEED = 'UPDATE_FINTECH_SUCCEED'
export const UPDATE_FINTECH_FAILED = 'UPDATE_FINTECH_FAILED'

export const INSERT_FINTECH = 'INSERT_FINTECH'
export const INSERT_FINTECH_SUCCEED = 'INSERT_FINTECH_SUCCEED'
export const INSERT_FINTECH_FAILED = 'INSERT_FINTECH_FAILED'

export const DELETE_FINTECH = 'DELETE_FINTECH'
export const DELETE_FINTECH_SUCCEED = 'DELETE_FINTECH_SUCCEED'
export const DELETE_FINTECH_FAILED = 'DELETE_FINTECH_FAILED'