export const FETCH_TRANSACTIONS = 'FETCH_TRANSACTIONS'
export const FETCH_TRANSACTIONS_FAILED = 'FETCH_TRANSACTIONS_FAILED'
export const FETCH_TRANSACTIONS_SUCCEED = 'FETCH_TRANSACTIONS_SUCCEED'

export const CREATE_TRANSACTION = 'CREATE_TRANSACTION'
export const CREATE_TRANSACTION_FAILED = 'CREATE_TRANSACTION_FAILED'
export const CREATE_TRANSACTION_SUCCEED = 'CREATE_TRANSACTION_SUCCEED'