export const FETCH_ACCOUNTS = "FETCH_ACCOUNTS";
export const FETCH_ACCOUNTS_FAILED = "FETCH_ACCOUNTS_FAILED";
export const FETCH_ACCOUNTS_SUCCEED = "FETCH_ACCOUNTS_SUCCEED";

export const FETCH_ACCOUNT = "FETCH_ACCOUNT";
export const FETCH_ACCOUNT_FAILED = "FETCH_ACCOUNT_FAILED";
export const FETCH_ACCOUNT_SUCCEED = "FETCH_ACCOUNT_SUCCEED";

export const CREATE_ACCOUNT = "CREATE_ACCOUNT";
export const CREATE_ACCOUNT_FAILED = "CREATE_ACCOUNT_FAILED";
export const CREATE_ACCOUNT_SUCCEED = "CREATE_ACCOUNT_SUCCEED";

export const UPDATE_ACCOUNT = "UPDATE_ACCOUNT";
export const UPDATE_ACCOUNT_FAILED = "UPDATE_ACCOUNT_FAILED";
export const UPDATE_ACCOUNT_SUCCEED = "UPDATE_ACCOUNT_SUCCEED";

export const DELETE_ACCOUNT = "DELETE_ACCOUNT";
export const DELETE_ACCOUNT_FAILED = "DELETE_ACCOUNT_FAILED";
export const DELETE_ACCOUNT_SUCCEED = "DELETE_ACCOUNT_SUCCEED";

export const CHECK_SECURED_KEY = "CHECK_SECURED_KEY";
export const CHECK_SECURED_KEY_FAILED = "CHECK_SECURED_KEY_FAILED";
export const CHECK_SECURED_KEY_SUCCEED = "CHECK_SECURED_KEY_SUCCEED";
