const purchasingTypes = {
    //Vendor Constant
    GET_VENDORS : 'GET_VENDORS',
    GET_VENDORS_SUCCEED : 'GET_VENDORS_SUCEED',
    GET_VENDORS_FAILED : 'GET_VENDORS_FAILED',
    ADD_VENDOR : 'ADD_VENDOR',
    ADD_VENDOR_SUCCEED : 'ADD_VENDOR_SUCCEED',
    ADD_VENDOR_FAILED : 'ADD_VENDOR_FAILED',
    UPDATE_VENDOR :'UPDATE_VENDOR',
    UPDATE_VENDOR_SUCCEED : 'UPDATE_VENDOR_SUCCEED',
    UPDATE_VENDOR_FAILED : 'UPDATE_VENDOR_FAILED',
    DELETE_VENDOR : 'DELETE_VENDOR',
    DELETE_VENDOR_SUCCEED : 'DELETE_VENDOR_SUCCEED',
    DELETE_VENDOR_FAILED : 'DELETE_VENDOR_FAILED',

    //Vendor Product Constant
    GET_VENDPRO : 'GET_VENDPRO',
    GET_VENDPRO_SUCCEED : 'GET_VENDPRO_SUCCEED',
    GET_VENDPRO_FAILED : 'GET_VENDPRO_FAILED',
    ADD_VENDPRO : 'ADD_VENDPRO',
    ADD_VENDPRO_SUCCEED : 'ADD_VENDPRO_SUCCEED',
    ADD_VENDPRO_FAILED : 'ADD_VENDPRO_FAILED',

    //Stocks Constant
    GET_STOCK :'GET_STOCK',
    GET_STOCK_SUCCEED : 'GET_STOCK_SUCCEED',
    GET_STOCK_FAILED : 'GET_STOCK_FAILED',
    ADD_STOCK : 'ADD_STOCK',
    ADD_STOCK_SUCCEED : 'ADD_STOCK_SUCCEED',
    ADD_STOCK_FAILED : 'ADD_STOCK_FAILED',
    UPDATE_STOCK : 'UPDATE_STOCK',
    UPDATE_STOCK_SUCCEED : 'UPDATE_STOCK_SUCCEED',
    UPDATE_STOCK_FAILED : 'UPDATE_STOCK_FAILED',

    //StockPhoto Constant
    GET_STOCK_PHOTO : 'GET_STOCK_PHOTO',
    GET_STOCK_PHOTO_SUCCEED : 'GET_STOCK_PHOTO_SUCCEED',
    GET_STOCK_PHOTO_FAILED : 'GET_STOCK_PHOTO_FAILED',
    ADD_STOCK_PHOTO : 'ADD_STOCK_PHOTO',
    ADD_STOCK_PHOTO_SUCCEED : 'ADD_STOCK_PHOTO_SUCCEED',
    ADD_STOCK_PHOTO_FAILED : 'ADD_STOCK_PHOTO_FAILED',
    GET_STOCK_PHOTO_DASHBOARD : 'GET_STOCK_PHOTO_DASHBOARD',
    GET_STOCK_PHOTO_DASHBOARD_SUCCEED :'GET_STOCK_PHOTO_DASHBOARD_SUCCEED',
    GET_STOCK_PHOTO_DASHBOARD_FAILED : 'GET_STOCK_PHOTO_DASHBOARD_FAILED',

    //StockDetails Constant
    GET_STOCK_DETAIL: 'GET_STOCK_DETAIL',
    GET_STOCK_DETAIL_SUCCEED : 'GET_STOCK_DETAIL_SUCCEED',
    GET_STOCK_DETAIL_FAILED : 'GET_STOCK_DETAIL_FAILED',
    EDIT_STOCK_DETAIL :'EDIT_STOCK_DETAIL',
    EDIT_STOCK_DETAIL_SUCCEED : 'EDIT_STOCK_DETAIL_SUCCEED',
    EDIT_STOCK_DETAIL_FAILED : 'EDIT_STOCK_DETAIL_FAILED',
    GET_FACI_NAME_AND_ID : 'GET_FACI_NAME_AND_DETAIL',
    GET_FACI_NAME_AND_ID_SUCCEED: 'GET_FACI_NAME_AND_ID_SUCCEED',
    GET_FACI_NAME_AND_ID_FAILED: ' GET_FACI_NAME_AND_ID_FAILED',

    //PurchaseOrder Constant
    GET_PURCHASE_ORDER : 'GET_PURCHASE_ORDER',
    GET_PURCHASE_ORDER_SUCCEED : 'GET_PURCHASE_ORDER_SUCCEED',
    GET_PURCHASE_ORDER_FAILED : 'GET_PURCHASE_ORDER_FAILED',
    ADD_PURCHASE_ORDER : 'ADD_PURCHASE_ORDER',
    ADD_PURCHASE_ORDER_SUCCEED : 'ADD_PURCHASE_ORDER_SUCCEED',
    ADD_PURCHASE_ORDER_FAILED : 'ADD_PURCHASE_ORDER_FAILED',
    EDIT_PURCHASE_ORDER : 'EDIT_PURCHASE_ORDER',
    EDIT_PURCHASE_ORDER_SUCCEED : 'EDIT_PURCHASE_ORDER_SUCCEED',
    EDIT_PURCHASE_ORDER_FAILED : 'EDIT_PURCHASE_ORDER_FAILED',

    //PurchaseOrderDetail Constant
    GET_PURCHASE_ORDER_DETAIL : 'GET_PURCHASE_ORDER_DETAIL',
    GET_PURCHASE_ORDER_DETAIL_SUCCEED : 'GET_PURCHASE_ORDER_DETAIL_SUCCEED',
    GET_PURCHASE_ORDER_DETAIL_FAILED :'GET_PURCHASE_ORDER_DETAIL_FAILED'
}

export default purchasingTypes