const ActionTypes = {
    // get card
    GET_CARDHOTEL: "GET_CARDHTEL",
    GET_CARDHOTEL_SUCCED: "GET_CARDHTEL_SUCCED",
    GET_CARDHOTEL_FAILED: "GET_CARDHTEL_FAILED",
  
    // get faciallhotel
    GET_FACIALLHOTEL: "GET_FACIALLHOTEL",
    GET_FACIALLHOTEL_SUCCED: "GET_FACIALLHOTEL_SUCCED",
    GET_FACIALLHOTEL_FAILED: "GET_FACIALLHOTEL_FAILED",
  
    // get hore
    GET_HORE: "GET_HORE",
    GET_HORE_SUCCED: "GET_HORE_SUCCED",
    GET_HORE_FAILED: "GET_HORE_FAILED",
  
    // get faci
    GET_FACIADMIN: "GET_FACIADMIN",
    GET_FACIADMIN_SUCCED: "GET_FACIADMIN_SUCCED",
    GET_FACIADMIN_FAILED: "GET_FACIADMIN_FAILED",
  
    // get max id room
    GET_MAXIDROOM: "GET_MAXIDROOM",
    GET_MAXIDROOM_SUCCED: "GET_MAXIDROOM_SUCCED",
    GET_MAXIDROOM_FAILED: "GET_MAXIDROOM_FAILED",
  
    //insert faci
    ADD_FACIADMIN: "ADD_FACIADMIN",
    ADD_FACIADMIN_SUCCED: "ADD_FACIADMIN_SUCCED",
    ADD_FACIADMIN_FAILED: "ADD_FACIADMIN_FAILED",
  
    // get search address
    GET_ADDRSEARCH: "GET_ADDRSEARCH",
    GET_ADDRSEARCH_SUCCED: "GET_ADDRSEARCH_SUCCED",
    GET_ADDRSEARCH_FAILED: "GET_ADDRSEARCH_FAILED",
  
    //Get Special Offer
    GET_SPECIAL_OFFERS: 'GET_SPECIAL_OFFERS',
    GET_SPECIAL_OFFERS_SUCCED: 'GET_SPECIAL_OFFERS_SUCCEES',
    GET_SPECIAL_OFFERS_FAILED: 'GET_SPECIAL_OFFERS_FAILED',
  
    //Get Master Items Price
    GET_PRICE_ITEMS : 'GET_PRICE_ITEMS',
    GET_PRICE_ITEMS_SUCCED : 'GET_PRICE_ITEMS_SUCCED',
    GET_PRICE_ITEMS_FAILED : 'GET_PRICE_ITEMS_FAILED',
  
    //Get Order Detail
    GET_ORDER_DETAILS : 'GET_ORDER_DETAILS',
    GET_ORDER_DETAILS_SUCCED : 'GET_ORDER_DETAILS_SUCCED',
    GET_ORDER_DETAILS_FAILED : 'GET_ORDER_DETAILS_FAILED',
  
    //Create Booking Order
    ADD_BOOKING_ORDER : 'ADD_BOOKING_ORDER',
    ADD_BOOKING_ORDER_SUCCED : 'ADD_BOOKING_ORDER_SUCCED',
    ADD_BOOKING_ORDER_FAILED : 'ADD_BOOKING_ORDER_FAILED',
  
    //GetInvoice
    GET_INVOICE : 'GET_INVOICE',
    GET_INVOICE_SUCCED : 'GET_INVOICE_SUCCED',
    GET_INVOICE_FAILED : 'GET_INVOICE_FAILED',

    //insert Boex
    ADD_BOEX : 'ADD_BOEX',
    ADD_BOEX_SUCCED : 'ADD_BOEX_SUCCED',
    ADD_BOEX_FAILED : 'ADD_BOEX_FAILED',

    //Get History Booking
    GET_HISTORY_BOOKING : 'GET_HISTORY_BOOKING',
    GET_HISTORY_BOOKING_SUCCED : 'GET_HISTORY_BOOKING_SUCCED',
    GET_HISTORY_BOOKING_FAILED: 'GET_HISTORY_BOOKING_FAILED',

    //Update Status Booking Order
    UPDATE_STATUS_BOOKING : 'UPDATE_STATUS_BOOKING',
    UPDATE_STATUS_BOOKING_SUCCED : 'UPDATE_STATUS_BOOKING_SUCCED',
    UPDATE_STATUS_BOOKING_FAILED : 'UPDATE_STATUS_BOOKING_FAILED'
  };
  
  export default ActionTypes;
  